---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sconfig
data:
  remotek8sconfig.yaml: |
    ---
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/remotek8s/ca.crt
        server: https://192.168.49.2:8443
      name: minikube
    contexts:
    - context:
        cluster: minikube
        namespace: default
        user: minikube
      name: minikube
    current-context: minikube
    kind: Config
    preferences: {}
    users:
    - name: minikube
      user:
        client-certificate: /etc/remotek8s/client.crt
        client-key: /etc/remotek8s/client.key
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIwMTIwOTE5MDIzOVoXDTMwMTIwODE5MDIzOVowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9t
    DEYIdfAAb4pdFaeQbUBzlHIpTg52uipfBIJbzsCjshW/7PDhDmpohMSDPVILYtng
    ajjtZg0vA2DcWJf3tpfsic6FgkHq+CZXMg6J34dNtPDpV4iYv03w1PIofZQ/kGrT
    PMsoA3lzMpbpFXMOcWqZjYdkyi3ROgRv+fXUluzcKcPeTuZ9xx0MT8bdtLrgk5AV
    FWwGsMJruD20nJjPHJN0yr5YP43ySRV3RDuyvgX5pHW3LfsdZqMsPFAaTVP5phGr
    7oPqOEeuIVl6Wared5ztrDXsASc/h/ekXkkYUdji+0chTjAtuDHR6rZKlZLEnJyu
    zft/gjHyVaNKThjVqzkCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQDQqUNVArXMa0Ex1qMUL/wxky36zANBgkqhkiG9w0BAQsFAAOCAQEAJX7AJxXR
    1Uf8UP/vNzkOKCpLlpsjeVEoxpOQ14dnYBA5PXjMzsPlC9VZ08CPNkJ3pqa1gsu6
    Z+7o4B6sNFnFLVFxt506AXnSYY63I6pI1EHjrFAehzMHqKz3fSgwRnJefj291zNB
    5J1BSwueIuWIPkGwd5E46mbV8F7LWzDAES0V+c0mZpxyxxZArab3Vucd7e0GWqIS
    pPVo2NiYEGxfRCCFuvhXZu+M8mY15rCmHozK37twsaZugAAqsjTA8WzO6ZmG4DMX
    ZRD1WyhdEyh8Y3z0TK6MA53lRsjl4lNJjdTcoJHP+4hJEpUTzRsjHrHOEiPS9Gvj
    rz9nUdE6DC5ysw==
    -----END CERTIFICATE-----
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIwMTIxOTIzNDU0N1oXDTIxMTIyMDIzNDU0N1owMTEXMBUGA1UE
    ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxVAhhJIuSxNeGrl8tvwwk7ob22wO8
    BM2rrE8kXdySbNh1btVBbrW3mmf/xpFTA5TokUxJMMty0IXPs7KqUoewuOPhe6jc
    7yHAcqfELWCK97mqhCV3809X+sQcMpRp+PY7o1I4oXN6eAeTu1czRNMNNjgEOtG+
    ZTj66/907HRNiiW1WMMRPaVduWPoaxBLLsjfxIlpn8pY7a/jkYgRYdKNF1dWeT/D
    ArRc8DAxxTLFncqqS8CIXL4doj3c6t7XAcGJ3Yvi8iUSz5ZEWCfMZ7UPhc6AjT4I
    B8K2P3E+cZr0MoAYVKZBPgFvatOECFn10V54d/qkJyIVPpDEZrFaim5xAgMBAAGj
    YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBQDQqUNVArXMa0Ex1qMUL/wxky3
    6zANBgkqhkiG9w0BAQsFAAOCAQEAnNUvfTYRisqUzy4Q1rO2Mc8eDq1cYF1l0O1X
    MfbGgcHX2NH2LxUMruFLHMfpFI5KRCoLQ0u5a/Cd1hetjMFUJ/HSdbNY8b5mGLPZ
    AePxIPMx/JVjMw0MyeCBDbGufolyycKF62wzQAxdHzzIPtDBEu46xmLchY5dhily
    ELgDGPvTx4qcvGzuFuGhveTumrc96rbTRfEt5QfTQ1QW872n6w3FDHSK93Zru/0O
    YCGpVhBORgl9VDoYUV/IiylgZN3moGOC6Nro9p/EDAdGQFW7sN/vDD2o5DdJWL8M
    8TLagPsZCZ1ws1IYTTnr+6kfzdH5So/gqvbHSRKhzP0HZM1Ixw==
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAsVQIYSSLksTXhq5fLb8MJO6G9tsDvATNq6xPJF3ckmzYdW7V
    QW61t5pn/8aRUwOU6JFMSTDLctCFz7OyqlKHsLjj4Xuo3O8hwHKnxC1give5qoQl
    d/NPV/rEHDKUafj2O6NSOKFzengHk7tXM0TTDTY4BDrRvmU4+uv/dOx0TYoltVjD
    ET2lXblj6GsQSy7I38SJaZ/KWO2v45GIEWHSjRdXVnk/wwK0XPAwMcUyxZ3KqkvA
    iFy+HaI93Ore1wHBid2L4vIlEs+WRFgnzGe1D4XOgI0+CAfCtj9xPnGa9DKAGFSm
    QT4Bb2rThAhZ9dFeeHf6pCciFT6QxGaxWopucQIDAQABAoIBAGPH4jMvSi5a/t+1
    DK+EGgRKB72t/Yr1tPlNqvbOrgfioWZq6Cq6bhwTEUQWar2ofUjkQWXJxCEl/rWh
    6v32FI43a1r8p0cyc+6DVa2IzxNDU8EEPMUjLtlVrLYlK+f5hCyIuQJOrtkR40mY
    l/esWYnMoXaX1l/pO0fONd+IEeVyz/MNrwY6ywwHxcLnGu+y2NxK9IV+PrZNVSj1
    aK50jp8cnv1o+1RB8qWvpKcniqf4efltjF5eos+CJuqhYkHkotNF/8a1h2q5SSPq
    C5qRCLe8PII+PHN3YGofk6/4LBGGa9Zp2ngKN+l4DP2V2qXO9yk27J0LBedm2j5r
    TVUnkzECgYEA2VgUAXu9/j+YyJsvo4PWQc//cFQWwB13OKfJj4URZTYPHofAS7eJ
    ABAz/gBxT0w3fzGwigETi2gpsPWoeLypMR7Dhwk5dKVdpKUJ7QBE9LNAeGAXj60V
    4fqBmehFuTOArp32c7NpWa78oOBgll43v4rtcbl7sqlwXZ2nsaW6970CgYEA0N39
    V+SHEJ+VPZZFEYcLKX8URAuGzZ/2M8TozVXKQjRnXHtyTKopG762uTHxtZAwcjVH
    eR3dX62ZU9sEv2x05Xjq3JM1n5dnkszYAsVwcbrj/LQf6jKEDmpIxAUqjj/h6O+n
    tsr4lJgMk4Y462gpQgPU0L0h+F6v0TDickfgksUCgYAidqz1b0G5Ryxa4wCy1Pzs
    gqbmkO7ql8GH4lM7xsXzXpcXKD99wiSfNfKInFlbUaKbMK3ltDX9LQ8vWETWoFPT
    ziUDDJtnu7EVonXodtp4UtQuQk56IeAObUKPvR0ROPF2vuWNgy15Yx38BJhMP7Rn
    UwhDuD29HtEKhy1IJhd3oQKBgQC0fxJfMSsTT4VOCp03b2dS/fHKd9ePvOurgz/X
    qoq2OckU380/uVD7HA2V7zY9PBTRrX9NiGR1OXUmRUBOGHDQmXUFFuYhO1sTPphx
    lKP+dI5vJE3sOqlqN6kYVIqZEVWt0eUyjybQarF7j2OC86mr1dnEZZ2EoHb5pXAb
    aEgHLQKBgQCYOf8eRsm8MQ0BJfToqp40Bkongv320wfW3ogflDpEnVDaUyvxD1pi
    obULGmQgQ8nzdb4Hy/9KfwhXV7KQvUCjCgQKIkCqmlt3abRnsGPrXQnGW1VzGG6V
    orVynKXTyvaNpgN3I7TQQckZ9dL3Vpa2BjrPVe+DYqLd0YxwVGvdbw==
    -----END RSA PRIVATE KEY-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipxe-deployment
spec:
  selector:
    matchLabels:
      app: ipxe
  replicas: 1
  template:
    metadata:
      labels:
        app: ipxe
    spec:
      volumes:
      - name: remotek8s
        configMap:
          name: k8sconfig
      containers:
      - name: ipxe-container
        image: ipxe-service:v0.3
        volumeMounts:
        - name: remotek8s
          mountPath: /etc/remotek8s
        env:
        - name: KUBECONFIG
          value: /etc/remotek8s/remotek8sconfig.yaml
        - name: CACRT
          value: /etc/remotek8s/ca.crt
        - name: CLIENTCRT
          value: /etc/remotek8s/client.crt
        - name: CLIENTKEY
          value: /etc/remotek8s/client.key
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ipxe-service
spec:
  selector:
    app: ipxe
  type: ClusterIP
  ports:
    - name: ipxe-port
      port: 80
      targetPort: 8082

