apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-crt
spec:
  secretName: ipxe-service-tls
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: "ipxe-service.local.ns1.fra3.infra.onmetal.de"
  isCA: true
  dnsNames:
  - "ipxe-service.local.ns1.fra3.infra.onmetal.de"
