apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: defaultreader7
rules:
- apiGroups: ["machine.onmetal.de"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipxe-service-read-defaultns7
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: defaultreader7
subjects:
- kind: ServiceAccount
  name: ipxe-service
  namespace: default


