apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default


patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ipxe-service

patches:
- path: cert_patch.json
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: selfsigned-crt

