{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
{{- $host := "" -}}
{{- if eq $.Values.location "fra3" }}
{{- $host = tpl ( .host.fra3 ) $ -}}
{{- else if eq $.Values.location "fra4" }}
{{- $host = tpl ( .host.fra4 ) $ -}}
{{- else }}
{{- fail "Please specify valid location (fra3, fra4, etc.) in .Values.yaml" }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-crt
spec:
  secretName: ipxe-service-tls
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: {{ $host }}
  isCA: true
  dnsNames:
  - {{ $host }}
{{- end }}
{{- end }}
