apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-inventory-94925a7e-d7e8-11ec-9bb5-3a68dd71f463
  namespace: metal-api-system
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUS......
        server: https://api.k8s.cluster:443
      name: onmetal
    contexts:
    - context:
        cluster: onmetal
        namespace: metal-api-system
        user: inventory-94925a7e-d7e8-11ec-9bb5-3a68dd71f463
      name: inventory-94925a7e-d7e8-11ec-9bb5-3a68dd71f463@onmetal
    current-context: inventory-94925a7e-d7e8-11ec-9bb5-3a68dd71f463@onmetal
    kind: Config
    preferences: {}
    users:
    - name: inventory-94925a7e-d7e8-11ec-9bb5-3a68dd71f463
      user:
        token: some-secret-token

