apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ips.ipam.metal.ironcore.dev
spec:
  group: ipam.metal.ironcore.dev
  names:
    plural: ips
    singular: ip
    kind: IP
    listKind: IPList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: IP is the Schema for the ips API
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: IPSpec defines the desired state of IP
              type: object
              required:
                - subnet
              properties:
                consumer:
                  description: Consumer refers to resource IP has been booked for
                  type: object
                  required:
                    - kind
                    - name
                  properties:
                    apiVersion:
                      description: APIVersion is resource's API group
                      type: string
                      maxLength: 253
                      minLength: 1
                      pattern: ^[a-z0-9]([-./a-z0-9]*[a-z0-9])?$
                    kind:
                      description: Kind is CRD Kind for lookup
                      type: string
                      maxLength: 63
                      minLength: 1
                      pattern: ^[A-Z]([-A-Za-z0-9]*[A-Za-z0-9])?$
                    name:
                      description: Name is CRD Name for lookup
                      type: string
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                ip:
                  description: IP allows to set desired IP address explicitly
                  type: string
                subnet:
                  description: >-
                    SubnetName is referring to parent subnet that holds
                    requested IP
                  type: object
                  properties:
                    name:
                      description: >-
                        Name of the referent. More info:
                        https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?
                      type: string
            status:
              description: IPStatus defines the observed state of IP
              type: object
              properties:
                message:
                  description: Message contains error details if the one has occurred
                  type: string
                reserved:
                  description: Reserved is a reserved IP
                  type: string
                state:
                  description: State is a network creation request processing state
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: IP
          type: string
          description: IP Address
          jsonPath: .status.reserved
        - name: Subnet
          type: string
          description: Subnet
          jsonPath: .spec.subnet.name
        - name: Consumer Group
          type: string
          description: Consumer Group
          jsonPath: .spec.consumer.apiVersion
        - name: Consumer Kind
          type: string
          description: Consumer Kind
          jsonPath: .spec.consumer.kind
        - name: Consumer Name
          type: string
          description: Consumer Name
          jsonPath: .spec.consumer.name
        - name: State
          type: string
          description: Processing state
          jsonPath: .status.state
        - name: Message
          type: string
          description: Message
          jsonPath: .status.message
  conversion:
    strategy: None
